services:
  pocketbase:
    image: ghcr.io/skylineagle/joystick/pb:latest
    network_mode: "host"
    restart: unless-stopped
    environment:
      - BAKER_URL=http://baker:3000
      - MEDIAMTX_API=http://mediamtx:9997
    volumes:
      - pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mediamtx:
    image: bluenviron/mediamtx:1.11.2
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  app:
    image: ghcr.io/skylineagle/joystick/app:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - pocketbase
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  joystick:
    image: ghcr.io/skylineagle/joystick/joystick:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.joystick
    restart: unless-stopped
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - SWITCHER_API_URL=http://switcher:8080
      - PORT=8000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  panel:
    image: ghcr.io/skylineagle/joystick/panel:latest
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.panel
    restart: unless-stopped
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - PORT=4000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  baker:
    image: ghcr.io/skylineagle/joystick/baker:latest
    network_mode: "host"
    restart: unless-stopped
    environment:
      - PORT=3000
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  switcher:
    image: ghcr.io/skylineagle/joystick/switcher:latest
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
      - PORT=8080
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  whisper:
    image: ghcr.io/skylineagle/joystick/whisper:latest
    network_mode: "host"
    restart: unless-stopped
    environment:
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
      - PORT=8081
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pb_data:
