services:
  traefik:
    image: traefik:v2.11
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    networks:
      - app-network

  pocketbase:
    image: ghcr.io/skylineagle/joystick/pb:latest
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8090:8090"
    environment:
      - BAKER_URL=http://baker:3000
      - MEDIAMTX_API=http://mediamtx:9997
    volumes:
      - pb_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mediamtx:
    image: bluenviron/mediamtx:1.11.2
    restart: unless-stopped
    ports:
      - "9997:9997" # API
      - "8554:8554" # RTSP
      - "8888:8888" # API and metrics
      - "8889:8889" # HLS
      - "1935:1935" # RTMP
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: ghcr.io/skylineagle/joystick/app:latest
    restart: unless-stopped
    platform: linux/amd64
    depends_on:
      - pocketbase
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  joystick:
    image: ghcr.io/skylineagle/joystick/joystick:latest
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - SWITCHER_API_URL=http://switcher:8080
      - PORT=8000
      - HOST=0.0.0.0
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joystick.rule=Host(`localhost`) && PathPrefix(`/joystick`)"
      - "traefik.http.middlewares.joystick-strip.stripprefix.prefixes=/joystick"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.joystick.middlewares=joystick-strip,cors"
      - "traefik.http.services.joystick.loadbalancer.server.port=8000"

  panel:
    image: ghcr.io/skylineagle/joystick/panel:latest
    restart: unless-stopped
    platform: linux/amd64
    # ports:
    #   - "4000:4000"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - PORT=4000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`localhost`) && PathPrefix(`/panel`)"
      - "traefik.http.middlewares.panel-strip.stripprefix.prefixes=/panel"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.panel.middlewares=panel-strip,cors"
      - "traefik.http.services.panel.loadbalancer.server.port=4000"

  baker:
    image: ghcr.io/skylineagle/joystick/baker:latest
    restart: unless-stopped
    platform: linux/amd64
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baker.rule=Host(`localhost`) && PathPrefix(`/baker`)"
      - "traefik.http.middlewares.baker-strip.stripprefix.prefixes=/baker"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.baker.middlewares=baker-strip,cors"
      - "traefik.http.services.baker.loadbalancer.server.port=3000"

  switcher:
    image: ghcr.io/skylineagle/joystick/switcher:latest
    restart: unless-stopped
    platform: linux/amd64
    # ports:
    #   - "8084:8084"
    environment:
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
      - PORT=8080
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.switcher.rule=Host(`localhost`) && PathPrefix(`/switcher`)"
      - "traefik.http.middlewares.switcher-strip.stripprefix.prefixes=/switcher"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.switcher.middlewares=switcher-strip,cords"
      - "traefik.http.services.switcher.loadbalancer.server.port=8080"

  whisper:
    image: ghcr.io/skylineagle/joystick/whisper:latest
    restart: unless-stopped
    platform: linux/amd64
    # ports:
    #   - "8081:8081"
    environment:
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
      - PORT=8081
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(`localhost`) && PathPrefix(`/whisper`)"
      - "traefik.http.middlewares.whisper-strip.stripprefix.prefixes=/whisper"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.whisper.middlewares=whisper-strip,cors"
      - "traefik.http.services.whisper.loadbalancer.server.port=8081"

  studio:
    image: ghcr.io/skylineagle/joystick/studio:latest
    restart: unless-stopped
    platform: linux/amd64
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
      - PORT=8001
    networks:
      - app-network
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studio.rule=Host(`localhost`) && PathPrefix(`/studio`)"
      - "traefik.http.middlewares.studio-strip.stripprefix.prefixes=/studio"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.studio.middlewares=studio-strip,cors"
      - "traefik.http.services.studio.loadbalancer.server.port=8001"

networks:
  app-network:
    driver: bridge

volumes:
  pb_data:
