services:
  pocketbase:
    image: ghcr.io/skylineagle/joystick/pb:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - BAKER_URL=http://baker:3000
      - MEDIAMTX_API=http://mediamtx:9997
    volumes:
      - pb_data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mediamtx:
    image: bluenviron/mediamtx:1.11.2
    restart: unless-stopped
    ports:
      - "9997:9997" # API
      - "8554:8554" # RTSP
      - "8888:8888" # API and metrics
      - "8889:8889" # HLS
      - "1935:1935" # RTMP
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  app:
    image: ghcr.io/skylineagle/joystick/app:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - pocketbase
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  joystick:
    image: ghcr.io/skylineagle/joystick/joystick:latest
    build:
      context: .
      dockerfile: Dockerfile.joystick
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - PORT=8000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  panel:
    image: ghcr.io/skylineagle/joystick/panel:latest
    build:
      context: .
      dockerfile: Dockerfile.panel
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - PORT=8080
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  baker:
    image: ghcr.io/skylineagle/switcher/baker:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MEDIAMTX_API=http://mediamtx:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  pb_data:
