x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-extra-hosts: &default-extra-hosts
  - "host.docker.internal:host-gateway"

x-networks: &default-networks
  - app-network

x-platform-restart: &default-platform-restart
  platform: linux/amd64
  restart: unless-stopped

x-cors-labels: &cors-labels
  - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
  - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
  - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
  - "traefik.http.middlewares.cors.headers.addvaryheader=true"

services:
  traefik:
    image: traefik:v2.11
    <<: *default-platform-restart
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    networks: *default-networks
    extra_hosts: *default-extra-hosts

  pocketbase:
    image: ghcr.io/skylineagle/joystick/pb:latest
    <<: *default-platform-restart
    ports:
      - "${POCKETBASE_PORT}:8090"
    environment:
      - BAKER_URL=${BAKER_URL}
      - MEDIAMTX_API=${MEDIAMTX_API}
    volumes:
      - pb_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging

  mediamtx:
    image: bluenviron/mediamtx:1.11.2
    network_mode: host
    <<: *default-platform-restart
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    logging: *default-logging

  app:
    image: ghcr.io/skylineagle/joystick/app:latest
    <<: *default-platform-restart
    depends_on:
      - pocketbase
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(${HOST:-localhost})"
      - "traefik.http.services.app.loadbalancer.server.port=${APP_INTERNAL_PORT}"

  joystick:
    image: ghcr.io/skylineagle/joystick/joystick:latest
    <<: *default-platform-restart
    environment:
      - STREAM_API_URL=${STREAM_API_URL}
      - POCKETBASE_URL=${POCKETBASE_URL}
      - SWITCHER_API_URL=${SWITCHER_API_URL}
      - PORT=${JOYSTICK_PORT}
      - HOST=${JOYSTICK_HOST}
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joystick.rule=Host(${HOST:-localhost}) && PathPrefix(`/joystick`)"
      - "traefik.http.middlewares.joystick-strip.stripprefix.prefixes=/joystick"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.joystick.middlewares=joystick-strip,cors"
      - "traefik.http.services.joystick.loadbalancer.server.port=${JOYSTICK_PORT}"

  panel:
    image: ghcr.io/skylineagle/joystick/panel:latest
    <<: *default-platform-restart
    environment:
      - POCKETBASE_URL=${POCKETBASE_URL}
      - PORT=${PANEL_PORT}
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(${HOST:-localhost}) && PathPrefix(`/panel`)"
      - "traefik.http.middlewares.panel-strip.stripprefix.prefixes=/panel"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.panel.middlewares=panel-strip,cors"
      - "traefik.http.services.panel.loadbalancer.server.port=${PANEL_PORT}"

  baker:
    image: ghcr.io/skylineagle/joystick/baker:latest
    <<: *default-platform-restart
    environment:
      - PORT=${BAKER_PORT}
      - STREAM_API_URL=${STREAM_API_URL}
      - POCKETBASE_URL=${POCKETBASE_URL}
      - JOYSTICK_API_URL=${JOYSTICK_API_URL}
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baker.rule=Host(${HOST:-localhost}) && PathPrefix(`/baker`)"
      - "traefik.http.middlewares.baker-strip.stripprefix.prefixes=/baker"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.baker.middlewares=baker-strip,cors"
      - "traefik.http.services.baker.loadbalancer.server.port=${BAKER_PORT}"

  switcher:
    image: ghcr.io/skylineagle/joystick/switcher:latest
    <<: *default-platform-restart
    environment:
      - STREAM_API_URL=${STREAM_API_URL}
      - POCKETBASE_URL=${POCKETBASE_URL}
      - JOYSTICK_API_URL=${JOYSTICK_API_URL}
      - PORT=${SWITCHER_PORT}
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.switcher.rule=Host(${HOST:-localhost}) && PathPrefix(`/switcher`)"
      - "traefik.http.middlewares.switcher-strip.stripprefix.prefixes=/switcher"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.switcher.middlewares=switcher-strip,cors"
      - "traefik.http.services.switcher.loadbalancer.server.port=${SWITCHER_PORT}"

  whisper:
    image: ghcr.io/skylineagle/joystick/whisper:latest
    <<: *default-platform-restart
    environment:
      - STREAM_API_URL=${STREAM_API_URL}
      - POCKETBASE_URL=${POCKETBASE_URL}
      - JOYSTICK_API_URL=${JOYSTICK_API_URL}
      - PORT=${WHISPER_PORT}
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(${HOST:-localhost}) && PathPrefix(`/whisper`)"
      - "traefik.http.middlewares.whisper-strip.stripprefix.prefixes=/whisper"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.whisper.middlewares=whisper-strip,cors"
      - "traefik.http.services.whisper.loadbalancer.server.port=${WHISPER_PORT}"

  studio:
    image: ghcr.io/skylineagle/joystick/studio:latest
    <<: *default-platform-restart
    environment:
      - POCKETBASE_URL=${POCKETBASE_URL}
      - JOYSTICK_API_URL=${JOYSTICK_API_URL}
      - PORT=${STUDIO_PORT}
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studio.rule=Host(${HOST:-localhost}) && PathPrefix(`/studio`)"
      - "traefik.http.middlewares.studio-strip.stripprefix.prefixes=/studio"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.studio.middlewares=studio-strip,cors"
      - "traefik.http.services.studio.loadbalancer.server.port=${STUDIO_PORT}"

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    ports:
      - "${DOZZLE_PORT}:8080"

networks:
  app-network:
    driver: bridge

volumes:
  pb_data:
