x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-extra-hosts: &default-extra-hosts
  - "host.docker.internal:host-gateway"

x-networks: &default-networks
  - app-network

x-platform-restart: &default-platform-restart
  platform: linux/amd64
  restart: unless-stopped

x-cors-labels: &cors-labels
  - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
  - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
  - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
  - "traefik.http.middlewares.cors.headers.addvaryheader=true"

services:
  traefik:
    image: traefik:v2.11
    <<: *default-platform-restart
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    networks: *default-networks
    extra_hosts: *default-extra-hosts

  pocketbase:
    image: ghcr.io/skylineagle/joystick/pb:latest
    <<: *default-platform-restart
    ports:
      - "8090:8090"
    environment:
      - BAKER_URL=http://baker:3000
      - MEDIAMTX_API=http://host.docker.internal:9997
      - JOYSTICK_API_URL=http://joystick:8000
      - JOYSTICK_API_KEY=dev-api-key-12345
    volumes:
      - pb_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging

  mediamtx:
    image: bluenviron/mediamtx:1.11.2
    network_mode: host
    <<: *default-platform-restart
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    logging: *default-logging

  app:
    image: ghcr.io/skylineagle/joystick/app:latest
    <<: *default-platform-restart
    depends_on:
      - pocketbase
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(${HOST:-localhost})"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  joystick:
    image: ghcr.io/skylineagle/joystick/joystick:latest
    <<: *default-platform-restart
    environment:
      - STREAM_API_URL=http://host.docker.internal:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - SWITCHER_API_URL=http://switcher:8080
      - PORT=8000
      - HOST=0.0.0.0
      - INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY:-dev}
      - INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY:-dev}
      - INNGEST_SERVE_URL=http://inngest:8288
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
      inngest:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joystick.rule=Host(${HOST:-localhost}) && PathPrefix(`/joystick`)"
      - "traefik.http.middlewares.joystick-strip.stripprefix.prefixes=/joystick"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.joystick.middlewares=joystick-strip,cors"
      - "traefik.http.services.joystick.loadbalancer.server.port=8000"

  inngest:
    image: inngest/inngest:latest
    <<: *default-platform-restart
    environment:
      - INNGEST_BASE_URL=http://${HOST:-localhost}/inngest
      - INNGEST_EVENT_KEY=${INNGEST_EVENT_KEY:-dev}
      - INNGEST_SIGNING_KEY=${INNGEST_SIGNING_KEY:-dev}
      - INNGEST_SERVE_PORT=8288
      - INNGEST_SQLITE_PATH=/var/lib/inngest/inngest.db
      - INNGEST_STATE_STORE_PATH=/var/lib/inngest/state
      - INNGEST_LOG_LEVEL=info
      - INNGEST_TELEMETRY_ENABLED=false
    volumes:
      - inngest_data:/var/lib/inngest
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    command: "inngest start -u http://joystick:8000/api/inngest"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8288/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inngest.rule=Host(${HOST:-localhost}) && PathPrefix(`/inngest`)"
      - "traefik.http.middlewares.inngest-strip.stripprefix.prefixes=/inngest"
      - "traefik.http.routers.inngest.middlewares=inngest-strip,cors"
      - "traefik.http.services.inngest.loadbalancer.server.port=8288"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=inngest
      - POSTGRES_USER=inngest
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inngest -d inngest"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  panel:
    image: ghcr.io/skylineagle/joystick/panel:latest
    <<: *default-platform-restart
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - PORT=4000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(${HOST:-localhost}) && PathPrefix(`/panel`)"
      - "traefik.http.middlewares.panel-strip.stripprefix.prefixes=/panel"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.panel.middlewares=panel-strip,cors"
      - "traefik.http.services.panel.loadbalancer.server.port=4000"

  baker:
    image: ghcr.io/skylineagle/joystick/baker:latest
    <<: *default-platform-restart
    environment:
      - PORT=3000
      - STREAM_API_URL=http://host.docker.internal:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baker.rule=Host(${HOST:-localhost}) && PathPrefix(`/baker`)"
      - "traefik.http.middlewares.baker-strip.stripprefix.prefixes=/baker"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.baker.middlewares=baker-strip,cors"
      - "traefik.http.services.baker.loadbalancer.server.port=3000"

  switcher:
    image: ghcr.io/skylineagle/joystick/switcher:latest
    <<: *default-platform-restart
    environment:
      - STREAM_API_URL=http://host.docker.internal:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
      - JOYSTICK_API_KEY=dev-api-key-12345
      - SLOT_HEALTH_CHECK_INTERVAL=30
      - PORT=8080
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.switcher.rule=Host(${HOST:-localhost}) && PathPrefix(`/switcher`)"
      - "traefik.http.middlewares.switcher-strip.stripprefix.prefixes=/switcher"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.switcher.middlewares=switcher-strip,cors"
      - "traefik.http.services.switcher.loadbalancer.server.port=8080"

  whisper:
    image: ghcr.io/skylineagle/joystick/whisper:latest
    <<: *default-platform-restart
    environment:
      - STREAM_API_URL=http://host.docker.internal:9997
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
      - PORT=8081
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whisper.rule=Host(${HOST:-localhost}) && PathPrefix(`/whisper`)"
      - "traefik.http.middlewares.whisper-strip.stripprefix.prefixes=/whisper"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.whisper.middlewares=whisper-strip,cors"
      - "traefik.http.services.whisper.loadbalancer.server.port=8081"

  studio:
    image: ghcr.io/skylineagle/joystick/studio:latest
    <<: *default-platform-restart
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
      - JOYSTICK_API_URL=http://joystick:8000
      - PORT=8001
    depends_on:
      pocketbase:
        condition: service_healthy
      mediamtx:
        condition: service_started
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studio.rule=Host(${HOST:-localhost}) && PathPrefix(`/studio`)"
      - "traefik.http.middlewares.studio-strip.stripprefix.prefixes=/studio"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      - "traefik.http.routers.studio.middlewares=studio-strip,cors"
      - "traefik.http.services.studio.loadbalancer.server.port=8001"

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks: *default-networks
    extra_hosts: *default-extra-hosts
    ports:
      - "8084:8080"

networks:
  app-network:
    driver: bridge

volumes:
  pb_data:
  inngest_data: {}
