FROM oven/bun:1.2.2
WORKDIR /app

RUN apt-get update && apt-get install -y sshpass

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
COPY . .
CMD ["bun", "run", "src/server/panel.ts"] 
