/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text_hook_name",
          max: 100,
          min: 1,
          name: "hook_name",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "select_event_type",
          maxSelect: 1,
          name: "event_type",
          presentable: false,
          required: true,
          system: false,
          type: "select",
          values: [
            "after_event_pulled",
            "after_all_events_pulled",
            "after_event_created",
            "after_event_deleted",
            "before_event_pull",
            "after_gallery_start",
            "after_gallery_stop",
          ],
        },
        {
          cascadeDelete: true,
          collectionId: "pbc_2153001328",
          hidden: false,
          id: "relation_device",
          maxSelect: 1,
          minSelect: 0,
          name: "device",
          presentable: false,
          required: false,
          system: false,
          type: "relation",
        },
        {
          cascadeDelete: true,
          collectionId: "pbc_2484833797",
          hidden: false,
          id: "relation_action",
          maxSelect: 1,
          minSelect: 0,
          name: "action",
          presentable: false,
          required: true,
          system: false,
          type: "relation",
        },
        {
          hidden: false,
          id: "json_parameters",
          maxSize: 0,
          name: "parameters",
          presentable: false,
          required: false,
          system: false,
          type: "json",
        },
        {
          hidden: false,
          id: "bool_enabled",
          name: "enabled",
          presentable: false,
          required: false,
          system: false,
          type: "bool",
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      id: "pbc_studio_hooks",
      indexes: [],
      listRule: null,
      name: "studio_hooks",
      system: false,
      type: "base",
      updateRule: null,
      viewRule: null,
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_studio_hooks");
    return app.delete(collection);
  }
);
